# Generated by Django 5.1.1 on 2024-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_thread_created', models.DateTimeField(auto_now=True)),
                ('thread_id', models.TextField(default='')),
                ('operator_id', models.IntegerField(default=0)),
                ('needed_operator', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
            ],
        ),
    ]
