# Generated by Django 5.1.1 on 2024-12-03 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_thread_created', models.DateTimeField(auto_now=True)),
                ('thread_id', models.TextField(default='')),
                ('operator_id', models.IntegerField(default=0)),
                ('needed_operator', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
