# Generated by Django 5.1.1 on 2024-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_open_ai_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
