# Generated by Django 5.1.1 on 2024-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_open_ai_bot_app', '0003_remove_botuser_username_botuser_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='date_thread_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
