# Generated by Django 5.1.1 on 2024-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_open_ai_bot_app', '0003_remove_botuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
