# Generated by Django 5.1.1 on 2024-10-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_open_ai_bot_app', '0002_botuser_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('sender_type', models.CharField(max_length=255)),
                ('message', models.TextField(default='')),
                ('chat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_open_ai_bot_app.botuser')),
            ],
        ),
    ]
