# Generated by Django 5.1.1 on 2024-12-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_open_ai_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=255)),
                ('sender_type', models.CharField(default='', max_length=255)),
                ('Message_Creation_Date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=255)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_open_ai_bot_app.botuser')),
            ],
        ),
    ]
