# Generated by Django 5.1.1 on 2024-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatviewer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chatviewer',
            name='message_type',
            field=models.TextField(default=''),
        ),
    ]
