# Generated by Django 5.1.1 on 2024-10-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatViewer', '0001_initial'),
        ('test_open_ai_bot_app', '0005_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatviewer',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_open_ai_bot_app.botuser'),
        ),
    ]
