# Generated by Django 5.1.1 on 2024-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatViewer', '0002_chatviewer_image_chatviewer_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatviewer',
            name='file_type',
            field=models.TextField(default=''),
        ),
    ]
